name: flutter_recipe_manager
description: "Recipe manager"
version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  get: 4.6.6
  flutter_form_builder: 9.4.1
  form_builder_validators: 11.0.0
  hive_ce: 2.5.0+2
  hive_ce_flutter: 2.0.0

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true